### PR TITLE
Prevent duplicate output

### LINKED ISSUE #374: Prevent duplicating stderr/stdout for `run_simple` commands
## Summary

When stderr+stdout announcing is enabled for `run_simple` in RSpec, both announcements are duplicated.

E.g. if a cli command outputs "hello world" in STDOUT, you'll see:

```
<<-STDOUT
hello world
STDOUT

<<-STDOUT
hello world
STDOUT
```
## Expected Behavior

If the command is only run once, it should print each stderr/stdout announcement only once.
## Current Behavior

Currently, the `stop()` call in `run_simple()` sends the notifications to announce the process's stderr+stdout. Then, `stop_all_commands` does the same.
## Possible Solution

The sanest "workaround" for now is: just temporarily disable announcing during the `stop` in run_simple. Since the output is gathered when the process ends anyway, this isn't a problem.

I implemented this in my own fork here:

https://github.com/e2/aruba/commit/c540485da24c71c1ad6fc3960b6211175e169943

Ideally, there should be a way to "consume" stderr/stdout during announcements. And ideally there would be a "streaming" of stderr/stdout live while the app is running.
## Steps to Reproduce (for bugs)
1. Aruba + RSpec
2. Activate announcing for `stdout`
3. `run_simple` with a simple 'hello world' script
4. You'll have the announcement appear twice (once for `stop` inside `run_simple`, and once for `stop_all_commands` when the test is done)
## Context

I want to see the output of commands - and it's annoying to get errors showing up multiple times on the screen. Especially annoying is having two sets of stdout+stderr. No to mention it's very confusing. (At first I though somehow the test ran twice).
## Your Environment

Project without cucumber (RSpec only, standard setup with `aruba init --test-framework=rspec`).

### PR DESCRIPTION
**Pull request by mvz**
## Summary

Ensure command output is only announced once.

## Details

During a run, `Command#stop` and `Command#terminate` are called multiple times, among other reasons to ensure all commands are actually terminated at the end of each spec or scenario.

If both general announcers and the announce-on-error functionality is used at the same time, duplicate output may still occur.

This includes changes from #399.

## Motivation and Context

This fixes #374.

## How Has This Been Tested?

Specs were added by @maxmeyer and myself to ensure stop events are only broadcast once on the event bus. The behavior was confirmed by running some of Aruba's features by hand and examining the entire output produced.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I've added tests for my code

### CODE REVIEW

File: spec/aruba/command_spec.rb [hunk 1]
```diff
@@ -0,0 +1,92 @@
...
+  let(:startup_wait_time) { 1 }
+
+  context '#started' do
+    before :each do
+      allow(event_bus).to receive(:notify).with(Events::CommandStarted)
+    end
+
+    before :each do
+      command.start
+    end
```
Comment (olleolleolle) [inline spec/aruba/command_spec.rb]: Communication: I think this is the "Act" step of Arrange-Act-Assert, and that it's not a `before`-test setup.

Suggestion: Move `command.start` into the `it`.

File: spec/aruba/command_spec.rb [hunk 2]
```diff
@@ -0,0 +1,92 @@
...
+  let(:working_directory) { expand_path('.') }
+  let(:environment) { ENV.to_hash }
+  let(:main_class) { nil }
+  let(:stop_signal) { nil }
+  let(:startup_wait_time) { 1 }
+
+  context '#started' do
+    before :each do
+      allow(event_bus).to receive(:notify).with(Events::CommandStarted)
+    end
```
Comment (olleolleolle) [inline spec/aruba/command_spec.rb]: `before :each` => `before` (this is the default; and it has been renamed in newer versions of RSpec; [`:each` is now `:example`](https://relishapp.com/rspec/rspec-core/v/3-7/docs/hooks/before-and-after-hooks))

**Comment by mvz** [comment]
@olleolleolle I made the changes you suggested, thanks.

**Comment by olleolleolle** [comment]
@mvz It's a pleasure to learn so much from the Aruba work you do here.

**Comment by maxmeyer** [comment]
@mvz Personally I prefer this type of specs, which are more "concise" as they use the Rspec syntax to define readable tests: http://www.betterspecs.org/.

**Comment by mvz** [comment]
@maxmeyer I have two problems with those type of tests:
* Using `subject` hides the nature of the object under test. Giving it an expressive name allows you to interpret the expectation itself more easily.
* Using an anonymous `it` block makes the intent of the test less clear: Yes, the method has the expected result, but why do we want it to have that result? Also, some desired outcomes cannot be expressed in RSpec syntax (e.g.,`it 'prevents #stop from notifying the event bus').

**Comment by olleolleolle** [comment]
@mvz In order to have the cake and eat it, explicitly naming the `subject` allows 


```ruby
let(:command) do
  described_class.new(
    'true',
    event_bus: event_bus,
    exit_timeout: exit_timeout,
    io_wait_timeout: io_wait_timeout,
    working_directory: working_directory,
    environment: environment,
    main_class: main_class,
    stop_signal: stop_signal,
    startup_wait_time: startup_wait_time
  )
end 
```

to be

```ruby
subject(:command) do
  described_class.new(
    'true',
    event_bus: event_bus,
    exit_timeout: exit_timeout,
    io_wait_timeout: io_wait_timeout,
    working_directory: working_directory,
    environment: environment,
    main_class: main_class,
    stop_signal: stop_signal,
    startup_wait_time: startup_wait_time
  )
end 
```

and, taking it a step further, passing the constructor parameters we're not manipulating in the test as primitive values would reduce "setup".

**Comment by maxmeyer** [comment]
@mvz Sorry, I was not very clear about that. I was a bit in a rush and didn't see, that that use `is_expected`. I don't like that style either, but try to avoid this.

I try to avoid using strings in the `it`-method.

~~~ruby
RSpec.describe MyClass do
  it 'some description' do
     expect(true).to_be true
  end
end
~~~

Instead I try to use something like that:

~~~ruby
RSpec.describe MyClass do
  subject(:my_instance) { described_class.new }

  context 'when action was run' do
    # Set state - if required
    before :example do
      my_instance.my_action
    end

    # Assert
     it { expect(my_instance.result).to_be true }
  end
end
~~~

I'm open to change the style to something which suits our needs best. But besides that, what I really want to see for our test suite: Use the same style we can commit to everywhere and don't mix styles. Example for the style current used at most places I had a look at: https://github.com/cucumber/aruba/blob/master/spec/aruba/api_spec.rb#L8-L18 vs.

**Comment by mvz** [comment]
@maxmeyer agreed on having a consistent style. I'll rewrite the examples and see how that goes.

**Comment by olleolleolle** [comment]
@maxmeyer Hi!

[rspec-its](https://github.com/rspec/rspec-its) is now a separate RubyGem.

Myron Marston wrote this, before its was removed: [Explanation for why `its` will be removed from rspec-3
](https://gist.github.com/myronmarston/4503509)

**Comment by maxmeyer** [comment]
@olleolleolle Thanks for clarifying that. Is there any place where we use this kind of style? I searched the repository and didn't find a place where we do this. Did I miss something?

First, I thought http://www.betterspecs.org/ recommends this style, but I can't find anything about `rspec-its` there either. It's nothing I used before. And reading Myron's writeup makes me thing, this is not a good way to go.

My style of writing RSpec specs was influenced by a talk. I think, it was this one: https://www.youtube.com/watch?v=d2gL6CYaYwQ. Though I don't use the `is_expected`-syntax for the reasons @mvz wrote down. 

The style recommended by this talk helps me to 
* concentrate on the way my code behaves in different contexts - using `#context "when something is given"`
* to DRY up my tests - though is goes "against" readability

But as you both are more into testing than me - my daily job is to keep things running as a sysadmin - I think you've got more experience than me and I'm happy to learn new things. :smile:

File: spec/aruba/command_spec.rb [hunk 3]
```diff
@@ -0,0 +1,87 @@
+require 'spec_helper'
+
+RSpec.describe Aruba::Command do
+  let(:command) do
```
Comment (maxmeyer) [inline spec/aruba/command_spec.rb]: As discussed: I prefer to use `subject(:command)` here.

File: spec/aruba/command_spec.rb [hunk 4]
```diff
@@ -0,0 +1,87 @@
...
+  let(:stop_signal) { nil }
+  let(:startup_wait_time) { 1 }
+
+  describe '#start' do
+    before do
+      allow(event_bus).to receive(:notify).with(Events::CommandStarted)
+    end
+
+    it 'leaves the command in the started state' do
+      command.start
```
Comment (maxmeyer) [inline spec/aruba/command_spec.rb]: I would place this in a separate `#before`-block`.

**Comment by olleolleolle** [comment]
@maxmeyer Now that we're trading video links, here's Searls, talking (very quickly) about testing:

- https://www.youtube.com/watch?v=aiDikM9g4x8
- https://www.youtube.com/watch?v=VD51AkG8EZw

**Comment by mvz** [comment]
@olleolleolle I updated the specs added one little fix for the InProcess runner. Can you take one final look at this?

**Comment by olleolleolle** [comment]
Great! Covering those bits is super good.
