### PR TITLE
Fix running commands on Windows (#387)

### LINKED ISSUE #387: Running commands on Windows is broken
## Summary

Running commands on windows seems to be broken. Have look at this [build](https://ci.appveyor.com/project/cucumberbdd/aruba/build/461/job/5u82fqffagc4f72o#L273). **Anyone using Ruby on Windows is welcome to help us fixing this.**

## Expected Behavior

Commands should be run on Windows.

## Current Behavior

Running commands fails on AppVeyor CI.

```
```
## Possible Solution

Fix code to run commands.

## Steps to Reproduce (for bugs)

See [CI Build](https://ci.appveyor.com/project/cucumberbdd/aruba/build/461/job/5u82fqffagc4f72o#L273)

## Your Environment

- Version used: latest
- Operating System and version: AppVeyor CI

### PR DESCRIPTION
**Pull request by dmitryfleytman**
## Summary

This pull request fixes #387 and makes aruba functional on Windows

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by dmitryfleytman** [comment]
Hello,

Have you had a chance to look at this yet?

Thanks in advance,
Dmitry

**Comment by dmitryfleytman** [comment]
Ping?

**Comment by dmitryfleytman** [comment]
Ping?

**Comment by thomthom** [comment]
I second this ping. This PR allowed me to run Aruba under Windows. It would be nice to be able to run a build from the main channel and not a custom patched version.

**Comment by dmitryfleytman** [comment]
For now, I pushed gem [aruba-win-fix](https://rubygems.org/gems/aruba-win-fix) with this PR applied.

File: lib/aruba/platforms/windows_command_string.rb [hunk 1]
```diff
@@ -16,7 +16,8 @@ def initialize(cmd)
 
       # Convert to array
       def to_a
-        Shellwords.split __getobj__
+        Shellwords.split( __getobj__.gsub('\\', 'ARUBA_TMP_PATHSEPARATOR') ).
```
Comment (maxmeyer) [inline lib/aruba/platforms/windows_command_string.rb]: Does this mean, `Shellwords` does not support windows correctly?

**Comment by maxmeyer** [comment]
Sorry for the delay. I oversaw that PR.

File: lib/aruba/platforms/windows_command_string.rb (hunk 1 above)
Comment (dmitryfleytman) [inline lib/aruba/platforms/windows_command_string.rb]: Yes, shellwords swallows windows path separators:

irb(main):001:0> require 'shellwords'
=> true
irb(main):002:0> Shellwords.split('c:\\windows\\system32')
=> ["c:windowssystem32"]

The solution in this PR is not very elegant, but it looks safe in given context.

A few more interesting observations:

This does not work:

irb(main):003:0> Shellwords.split('c:\\windows\\system32'.gsub('\\', '\\\\'))
=> ["c:windowssystem32"]

While this does work:

irb(main):004:0> Shellwords.split('c:\\windows\\system32'.gsub('\\', '\\\\\\\\'))
=> ["c:\\windows\\system32"]

So it might be solution as well, however it looks too subtle...

**Comment by dmitryfleytman** [comment]
@maxmeyer, no problem, thanks for looking at it.

**Comment by dmitryfleytman** [comment]
Hi @maxmeyer , have you seen my comment regarding the proposed to_a implementation?

**Comment by maxmeyer** [comment]
@dmitryfleytman Yes, I saw you comment. But right now, I'm busy. I hope to find some time in mid June to wrap my head around that problem.

File: lib/aruba/platforms/windows_command_string.rb (hunk 1 above)
Comment (maxmeyer) [inline lib/aruba/platforms/windows_command_string.rb]: What about replacing `\` by `/` instead? Looks more obvious where the problem is.

**Comment by maxmeyer** [comment]
Sorry for the delay, what do you think about my proposal?

**Comment by dmitryfleytman** [comment]
@maxmeyer, I would not recommend replacing `\\` by `/` because `/` is widely used on Windows for command line switches, like `copy /Y /N ...`.

Should I put a comment with explanations into the `to_a` instead?

**Comment by dmitryfleytman** [comment]
@maxmeyer, have you seen my reply?

**Comment by dmitryfleytman** [comment]
Thanks, @maxmeyer 

Would you mind releasing a new version?
