### PR TITLE
Replace run methods

### LINKED ISSUE #559: Officially deprecate #run and #run_simple in the 0.14.x series
## Summary

The `#run` and `#run_simple` methods were removed from master, but are still present without deprecation on 0.14.x. Our aim is to deprecated each method before removing it, so something will have to be done.

## Current Behavior

~~~
~~~

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Operating System and version:
* Link to your project:

### PR DESCRIPTION
**Pull request by mvz**
## Summary

Fix #559.

## Details

Deprecates `#run` and `#run_simple` in favor of `#run_command` and `#run_command_and_stop`, and uses the new methods everywhere.

## Motivation and Context

Makes the eventual transition to 1.0 smoother for users.

## How Has This Been Tested?

Full suite has been run to check for (deprecation) errors.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (cleanup of codebase without changing any existing functionality)
- [x] Update documentation

## Checklist:

- [ ] I've added tests for my code
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

File: lib/aruba/api/deprecated.rb [hunk 1]
```diff
@@ -116,13 +116,75 @@ def eot
       #   The command to by run
       #
       # @see #cmd
-      # @deprectated
+      # @deprecated
```
Comment (olleolleolle) [inline lib/aruba/api/deprecated.rb]: Good find!
